### ISSUE TITLE
CNS tags should be serialized as Instance tags not Go structs

### ISSUE THREAD

**Issue by cheapRoc** [joyent/triton-service-groups#78]
Reported by: @geek 

When listing a group's instances there is a bug with how we handle CNS values. TSG is returning a serialized representation of CNS Go structs instead of the CNS tags normally found on instances coming out of Triton's CloudAPI. This is due to the output of `triton-go` being re-serialized into JSON.

The `GET /v1/tsg/groups/{UUID}/instances` endpoint currently outputs the following...

```json
"CNS": {
    "Disable": false,
    "ReversePTR": "",
    "Services": ["foo", "bar"]
}
```

[Special CNS tags](https://apidocs.joyent.com/docker/divergence#container-labels) are normally returned on an Instance object like...

```json
"tags": {
    "triton.cns.disable": false,
    "triton.cns.reverse_ptr": "",
    "triton.cns.services": "foo,bar"
},
```

**Comment by kwilczynski** [comment]
Hi @geek!

This one is quite tricky to fix, as we do a "store and forward" (which has some cost to it) rather than "proxy" of the payload form the CloudAPI. Same goes to the `HEAD` request - we would have to either receive a whole payload (to get the bytes for the `Content-Size`) or find a way to proxy this over to the CloudAPI, so for either `GET` or `HEAD` here, there is a lot of leg work which has to be done to pass these details over the you, where you can make the request yourself, so to speak.

We could solve this problem by implementing a full-blown CloudAPI client aside of SDK we already use, but it would still be a lot of work, where you could call the CloudAPI directly and use a `tsg.name` tag with the name of the group as a filter entity (for a given account, that is).

Which is why I am going to close this for now. Perhaps we will remove this end-point, given how quirky it is to get right.

Apologies for the inconvenience caused!
